### ISSUE TITLE
“MavensMate.app” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by NWilliamsSCU** [joeferraro/MavensMate-app#100] opened 2015-10-24 22:53 UTC
I get this error when I try to open MavensMate.app (v10)

**Comment by joeferraro** [comment] 2015-10-25 01:08
duplicate of https://github.com/joeferraro/MavensMate-app/issues/94

**Closed by joeferraro** 2015-10-25 01:08 UTC
